# Generated by Django 6.0 on 2025-12-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_status', models.CharField(max_length=20)),
                ('d_date', models.DateField()),
                ('ord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
