# Generated by Django 6.0 on 2025-12-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_invoice_no', models.CharField(max_length=50)),
                ('p_method', models.CharField(max_length=30)),
                ('p_status', models.CharField(max_length=20)),
                ('p_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
