# Generated by Django 6.0 on 2025-12-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('a_fullname', models.CharField(max_length=100)),
                ('a_login_name', models.CharField(max_length=50)),
                ('a_password', models.CharField(max_length=255)),
                ('a_email', models.EmailField(max_length=100)),
                ('a_phone', models.CharField(max_length=15)),
                ('a_gender', models.CharField(max_length=10)),
                ('a_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_fullname', models.CharField(max_length=100)),
                ('c_login_name', models.CharField(max_length=50)),
                ('c_password', models.CharField(max_length=255)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_phone', models.CharField(max_length=15)),
                ('c_gender', models.CharField(max_length=10)),
                ('c_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_fullname', models.CharField(max_length=100)),
                ('f_login_name', models.CharField(max_length=50)),
                ('f_password', models.CharField(max_length=255)),
                ('f_email', models.EmailField(max_length=100)),
                ('f_phone', models.CharField(max_length=15)),
                ('f_gender', models.CharField(max_length=10)),
                ('f_address', models.TextField()),
            ],
        ),
    ]
