# Generated by Django 6.0 on 2025-12-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/farmers/'),
        ),
    ]
