# Generated by Django 6.0 on 2026-01-05 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='ord_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
