# Generated by Django 6.0 on 2025-12-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pr_id', models.AutoField(primary_key=True, serialize=False)),
                ('pr_name', models.CharField(max_length=100)),
                ('pr_category', models.CharField(max_length=50)),
                ('pr_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_stock_qty', models.IntegerField()),
                ('pr_description', models.TextField()),
                ('pr_status', models.CharField(max_length=20)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.farmer')),
            ],
        ),
    ]
