# Generated by Django 6.0 on 2025-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pr_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
